# Generated by Django 5.0.6 on 2024-07-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_unitofmeasurement_remove_product_uom_stockout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='batch_id',
            field=models.CharField(default='', max_length=4, unique=True),
        ),
    ]
