# Generated by Django 5.0.6 on 2024-07-06 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockin_batch_id'),
    ]

    operations = [
    ]
